columns:
  - eid: str
  - Name: str
  - Project Code: str
  - Project Description: str
  - Description: str
  - Function: str
  - Site: str
  - Client facing: str
  - state: str
  - createdAt : str
  - editedAt: str
  - firstName: str
  - lastName: str
  # - email: str
  - acceptedAt: str
